#!/bin/bash

CTD_DIR=$HOME/Checkouts/PhD/data/processed/ss9802/ctd
ADCP_DIR=$HOME/Checkouts/PhD/data/processed/ss9802/adcp

source activate ocean36

python data/ctd_csv2nc.py # && ncdump -h $CTD_DIR/ss9802_ctd.nc
python data/ctd_gsw.py # && ncdump -h $CTD_DIR/ss9802_ctd_gsw.nc
python models/create_gem.py 

source activate ocean2
python data/ctd_gsw.py && ncdump -h $CTD_DIR/ss9802_ctd_gsw.nc
python models/create_gem.py && ncdump -h $CTD_DIR/ss9802_ctd_gem.nc

source activate ocean36

python data/adcp_csv2nc.py
python data/adcp_ctd.py && ncdump -h $ADCP_DIR/ss9802_adcp_ctd.nc
